openapi: 3.1.0
info:
  title: Whether Example API
  description: ''
  license:
    name: ''
  version: '1.0'
paths:
  /api/v1/weather:
    get:
      tags:
      - weather
      summary: Get Current Weather
      description: Returns current weather for given coordinates
      operationId: handle_get_current_weather
      parameters:
      - name: lat
        in: query
        description: Latitude
        required: true
        schema:
          type: string
          default: '18.300231990440125'
      - name: lon
        in: query
        description: Longitude
        required: true
        schema:
          type: string
          default: '-64.8251590359234'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse_CurrentWeather'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
components:
  schemas:
    CurrentWeather:
      type: object
      required:
      - temperature
      properties:
        temperature:
          type: string
          examples:
          - '0.0'
    StatusResponse:
      type: object
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
          examples:
          - $serde_json::private::Number: '0'
          minimum: 0
        message:
          type: string
    SuccessResponse_CurrentWeather:
      type: object
      required:
      - code
      - message
      - data
      properties:
        code:
          type: integer
          format: int32
          examples:
          - $serde_json::private::Number: '200'
          minimum: 0
        data:
          type: object
          required:
          - temperature
          properties:
            temperature:
              type: string
              examples:
              - '0.0'
        message:
          type: string
